### ISSUE TITLE
Unimap created the unimap_logs folder with the --no-keep-nmap-logs flag

### ISSUE THREAD

**Issue by gprime31** [Edu4rdSHL/unimap#11]
can you make it not write the unimap_logs folder when using the --no-keep-nmap-logs flag ?

command:
unimap --fast-scan -f subdomains.txt --ports 80,443 -q --url-output --no-keep-nmap-logs

**Comment by Edu4rdSHL** [comment]
This will create the folder and write the logs to analyze post-scan and generate the graphic. Maybe what you want is to make it delete the folder if the option is passed.

**Comment by gprime31** [comment]
that will work.

**Comment by Edu4rdSHL** [comment]
Done.
