### ISSUE TITLE
addr2line

### ISSUE THREAD

**Issue by necrose99** [Edu4rdSHL/unimap#2]
https://crates.io/crates/addr2line
addr2line = "0.15.1"
 - Add the [`addr2line` crate](https://crates.io/crates/addr2line) to your `Cargo.toml`

while i can do this locally .... and run [cargo ebuild](https://github.com/cardoe/cargo-ebuild) , [repoman](https://wiki.gentoo.org/wiki/Repoman) won't add the crate then generate manifest goodness...  if i do not add to toml file.. 

hopefully this will fix it for everyone....

**Comment by Edu4rdSHL** [comment]
Hello, I'm able to build locally with `cargo build`, can you please explain why do you need this change? It's some Gentoo-specific thing?

Thank you.

**Comment by necrose99** [comment]
https://crates.io/crates/unimap/versions  newer versions are not published yet to index. 
[net-analyzer_unimap.zip](https://github.com/Edu4rdSHL/unimap/files/6488040/net-analyzer_unimap.zip)

I rebooted to real install , need to scrape VMware install/ rebuild wget to pull crates is getting flaky... 

however its catching on src dir 

anyway ebuild is used to run cargo build in sandbox > push package /usr/bin or etc.. 

need to add 
https://github.com/Edu4rdSHL/unimap/ egit and commit tags in some sane way for newer as it's not playing nice.

**Comment by Edu4rdSHL** [comment]
I'm not going to publish they to crates.io anymore, it's a problem when you have to add your own crate fork to dependencies and then you aren't able to publish anymore there. Happened with Findomain and I had to yank more than 30 releases.

**Comment by necrose99** [comment]
still working on build script
