### ISSUE TITLE
Is it possible to give specific ports?

### ISSUE THREAD

**Issue by th33phoenix** [Edu4rdSHL/unimap#6]
hey there!!!
I see there is option to specify a range of ports --iport and --lport. But I don't see any option to specify some specific ports while scanning. For example, if I want to only scan for ports 80,443,8080,8443, how do I do that?
Thank you

**Comment by Edu4rdSHL** [comment]
Hello, Unimap doesn't have the `--iport` and `--lport` options (that's Findomain) but instead the `--ports` one and yes, you can specify custom ports, for example `--ports "22,80,443,3036,4443"`, also ranges, for example `--ports "22-80,443-3036,4443"` (note the quotes in the ports numbers).

You can specify ports in the same way that you do with Nmap, the same formats are supported because we basically pass the `--ports` string to the Nmap's `-p` option, that's why the quotes are required.

**Comment by th33phoenix** [comment]
Hello
Then why do I see the options --iport and --lport, and not --ports in unimap help section? 
![322868_1100-800x825](https://user-images.githubusercontent.com/95338141/148071891-02d024df-4f03-4db5-b63e-fb49c204b5f8.jpg)
![Screenshot_20220104_194207](https://user-images.githubusercontent.com/95338141/148071896-0025dd11-fa7e-4f6d-8d82-683671ab5594.png)
![Screenshot_20220104_194317](https://user-images.githubusercontent.com/95338141/148071900-edf6f925-7957-4722-8111-c32fdad95b2f.png)

**Comment by th33phoenix** [comment]
Hello
Then why do I see the options --iport and --lport, and not --ports in unimap help section?
![Screenshot_20220104_194207](https://user-images.githubusercontent.com/95338141/148072007-191c8113-2f22-479c-9e28-8c373a79b1d6.png)
![Screenshot_20220104_194317](https://user-images.githubusercontent.com/95338141/148072011-5bb38909-3c2e-445f-8b9a-cb07d9badb3f.png)

**Comment by Edu4rdSHL** [comment]
That's from several versions ago, if you look at the screenshot the version is 0.2.0, latest version is 0.5.1.

**Comment by th33phoenix** [comment]
Ok. So sorry about that. I don't know how older version got installed. Thank you so much for the quick reply. Sorry about the confusion

**Comment by Edu4rdSHL** [comment]
Probably from crates.io, I will fix some documentation right now, use the binaries from the releases section or build it directly cloning the repo.

**Comment by th33phoenix** [comment]
Yes, I used crates.io to install. But I have uninstalled it now and install from arch package, which has latest version. Thank you very much. I should have used the arch package.
