### ISSUE TITLE
Cargo Build Release fails on dependency

### ISSUE THREAD

**Issue by notcorkster** [Edu4rdSHL/unimap#7]
$ cargo build --release
...

error: failed to get `trust-dns-resolver` as a dependency of package `unimap v0.5.1 (<filepath>/unimap)`

Caused by:
  failed to load source for dependency `trust-dns-resolver`

Caused by:
  Unable to update https://github.com/Edu4rdSHL/trust-dns?branch=main#451a00fb

Caused by:
  failed to fetch into: <filepath>/.cargo/git/db/trust-dns-bd6b3a67144b30b7

Caused by:
  process didn't exit successfully: `git fetch --force --update-head-ok 'https://github.com/Edu4rdSHL/trust-dns' 'refs/heads/main:refs/remotes/origin/main'` (exit status: 128)
  --- stderr
  remote: Repository not found.
  fatal: repository 'https://github.com/Edu4rdSHL/trust-dns/' not found

**Comment by Edu4rdSHL** [comment]
Hello, thank you for reporting it, the issue has been fixed.
